/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.common;

import com.mysql.cj.protocol.Resultset;
import db.PersonManager;
import helper.constant.CompanyTypes;
import helper.constant.UserRole;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import ui.manager.UIManager;

/**
 *
 * @author shreyajaiswal
 */
public class CompanyLoginPanel extends javax.swing.JPanel {
String userType = "";
//String adminRole

    /**
     * Creates new form CompanyLoginPanel
     */
    public CompanyLoginPanel(String userType) {
//        
//    public static final String PHARMACY_ADMIN = "PHARMACY_ADMIN";
//    public static final String PHARMACY_STORE_MANAGER = "STORE_ADMIN";
//    public static final String CUSTOMER = "CUSTOMER";
//    public static final String MANUFACTURE_ADMIN = "MANUFACTURE_ADMIN";
//    public static final String DISTRIBUTOR_ADMIN = "DISTRIBUTOR_ADMIN";
//    public static final String DISTRIBUTOR_TRANSPORT_MANAGER = "DISTRIBUTOR_TRANSPORT_ADMIN";
//    public static final String MANUFACTURE_PRODUCT_MANAGER = "MAN_PRODUCT_ADMIN"
        
        
        initComponents();
        this.userType = userType;
        
        if(this.userType.equalsIgnoreCase(UserRole.MANUFACTURE_ADMIN)||(this.userType.equalsIgnoreCase(CompanyTypes.MANUFACTURER)))
        {
            jComboBoxLoginRole.removeAllItems();
            jComboBoxLoginRole.addItem("MANUFACTURE_ADMIN");
            jComboBoxLoginRole.addItem("MAN_PRODUCT_ADMIN");
        }
        else if(this.userType.equalsIgnoreCase(UserRole.PHARMACY_ADMIN)||(this.userType.equalsIgnoreCase(CompanyTypes.PHARMACY)))
        {
            jComboBoxLoginRole.removeAllItems();
            jComboBoxLoginRole.addItem("PHARMACY_ADMIN");
            jComboBoxLoginRole.addItem("PHARMACY_STORE_MANAGER");
        }
        
        else if(this.userType.equalsIgnoreCase(UserRole.DISTRIBUTOR_ADMIN)||(this.userType.equalsIgnoreCase(CompanyTypes.DISTRIBUTOR)))
        {
            jComboBoxLoginRole.removeAllItems();
            jComboBoxLoginRole.addItem("DISTRIBUTOR_ADMIN");
            jComboBoxLoginRole.addItem("DISTRIBUTOR_TRANSPORT_ADMIN");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxLoginRole = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldUserName = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 153));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Login"));

        jLabel2.setText("LOGIN AS");

        jLabel3.setText("USERNAME");

        jComboBoxLoginRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PHARMACY_ADMIN", "Pharmacy_Store_Manager", "Distributor_Administrator", "Distributor_Transport_Manager", "MANUFACTURE_ADMIN", "Manufacturer_Product_Manager" }));
        jComboBoxLoginRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLoginRoleActionPerformed(evt);
            }
        });

        jLabel4.setText("PASSWORD");

        jTextFieldUserName.setText("user");
        jTextFieldUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUserNameActionPerformed(evt);
            }
        });

        jPasswordField1.setText("password");
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxLoginRole, 0, 277, Short.MAX_VALUE)
                    .addComponent(jTextFieldUserName)
                    .addComponent(jPasswordField1))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxLoginRole, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Marker Felt", 0, 18)); // NOI18N
        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Marker Felt", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN PORTAL");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(226, 226, 226)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 61, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxLoginRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLoginRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxLoginRoleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//    public static final String PHARMACY_ADMIN = "PHARMACY_ADMIN";
//    public static final String PHARMACY_STORE_MANAGER = "PHARMACY_STORE_MANAGER";
//    public static final String CUSTOMER = "CUSTOMER";
//    public static final String MANUFACTURE_ADMIN = "MANUFACTURE_ADMIN";
//    public static final String DISTRIBUTOR_ADMIN = "DISTRIBUTOR_ADMIN";
//    public static final String DISTRIBUTOR_TRANSPORT_MANAGER = "DISTRIBUTOR_TRANSPORT_ADMIN";
//    public static final String MANUFACTURE_PRODUCT_MANAGER = "MAN_PRODUCT_ADMIN"

String username = jTextFieldUserName.getText();
String password = jPasswordField1.getText();
//String loginRole = jComboBoxLoginRole.getSelectedItem().toString(); 

try {
    ResultSet rs = PersonManager.verifyUser(username, password,userType);
    if (rs.next()) {
        String verifiedUsername = rs.getString("username");
        int verifiedCompanyId = rs.getInt("company_id");
        String loginRole = rs.getString("person_role");

        switch(loginRole) {
            case UserRole.MANUFACTURE_ADMIN:
                UIManager.AddManuAdminPanel(verifiedUsername, verifiedCompanyId); 
              break;
            case UserRole.PHARMACY_ADMIN:
                UIManager.AddpharmacyAdminPanel(verifiedUsername, verifiedCompanyId);    
              break;
            default:
              // code block
        }

         {
         }

    //     else if(loginRole.equalsIgnoreCase("PHARMACY_ADMIN"))
    //     {
    //       UIManager.AddpharmacyAdminPanel();
    //     }
    //     else if(loginRole.equalsIgnoreCase("PHARMACY_ADMIN"))
    //     {
    //       UIManager.AddpharmacyAdminPanel();
    //     }
    //     else if(loginRole.equalsIgnoreCase(UserRole.PHARMACY_ADMIN))
    //    {
    //    }
    //    else if(loginRole.equalsIgnoreCase(UserRole.PHARMACY_STORE_MANAGER)){
    //        UIManager.AddpharmacyStorePanel();
    //    }
    } else throw new Exception("No User Found");
} catch(Exception e) {
 JOptionPane.showMessageDialog(this, e);
}


        
       
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
UIManager.AddCompanyManagerPanel(userType);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextFieldUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUserNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBoxLoginRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextFieldUserName;
    // End of variables declaration//GEN-END:variables
}
